[[pages]]
path = "overview.py"
name = "Home"
icon = ":house:"

[[pages]]
path = "01_Dashboard.py"
name = "Dashboard"
icon = "ğŸ“ˆ"

[[pages]]
path = "04_Deep Analysis.py"
name = "Deep Analysis"
icon = "ğŸ•µï¸â€â™‚ï¸"

[[pages]]
path = "02_Knowledge Check.py"
name = "Knowledge Check"
icon = "â˜‘ï¸"

[[pages]]
path = "03_Personal Pollution Tracker.py"
name = "Personal Pollution Tracker"
icon = "ğŸ”–"

[[pages]]
path = "05_Feedback.py"
name = "Feedback"
icon = "ğŸ“£"